# LAB - Tính toán các chỉ số đánh giá từ Ma trận Nhầm lẫn

## Giới thiệu
Trong học máy và các bài toán phân loại, **ma trận nhầm lẫn** (Confusion Matrix) là một công cụ giúp đánh giá chất lượng của mô hình dự đoán. Ma trận này cho thấy kết quả dự đoán đúng và sai của mô hình.

Một ma trận nhầm lẫn cơ bản cho bài toán phân loại nhị phân có dạng:

$$
\begin{bmatrix}
TN & FP \\
FN & TP \\
\end{bmatrix}
$$

### Ý nghĩa các chỉ số trong ma trận nhầm lẫn
- **True Negative (TN)**: Số lượng mẫu thực tế là **âm** (Negative) và mô hình cũng dự đoán là **âm**.
- **False Positive (FP)**: Số lượng mẫu thực tế là **âm** nhưng mô hình lại dự đoán là **dương** (Positive). Đây còn gọi là **dương giả**.
- **False Negative (FN)**: Số lượng mẫu thực tế là **dương** nhưng mô hình lại dự đoán là **âm**. Đây còn gọi là **âm giả**.
- **True Positive (TP)**: Số lượng mẫu thực tế là **dương** và mô hình cũng dự đoán là **dương**.

Các giá trị này có thể tính toán được nhiều chỉ số quan trọng, giúp đánh giá mô hình một cách toàn diện.

## Các Chỉ số Đánh giá Hiệu quả Mô Hình

### 1. Độ chính xác (Accuracy)
**Độ chính xác** là tỷ lệ số dự đoán đúng trên tổng số mẫu. Chỉ số này cho biết mô hình dự đoán chính xác bao nhiêu phần trăm.
$$
\text{Accuracy} = \frac{TP + TN}{TP + TN + FP + FN}
$$

### 2. Độ nhạy (Recall) 
**Độ nhạy** hay còn gọi là **Tỷ lệ phát hiện dương** (Sensitivity) cho biết mô hình phát hiện đúng bao nhiêu phần trăm các mẫu dương. Độ nhạy đặc biệt quan trọng khi chúng ta muốn giảm thiểu số trường hợp **âm giả**.
$$
\text{Recall} = \frac{TP}{TP + FN}
$$

Ví dụ, nếu đang xây dựng mô hình chẩn đoán bệnh, Recall cao có nghĩa là mô hình không bỏ sót quá nhiều ca bệnh.

 Giải thích :
- recall là tỷ lệ phát hiện đúng các mẫu dương.
- Trong trường hợp chẩn đoán bệnh, các mẫu dương là các ca bệnh thực sự.
- recall cao có nghĩa là mô hình phát hiện được hầu hết các ca bệnh, tức là không bỏ sót nhiều ca bệnh

### 3. Độ đặc hiệu (Specificity)
**Độ đặc hiệu** là tỷ lệ dự đoán đúng các mẫu âm trên tổng số các mẫu âm thực tế. Chỉ số này cho biết mô hình có khả năng nhận diện đúng các mẫu âm tốt như thế nào.
$$
\text{Specificity} = \frac{TN}{TN + FP}
$$

Ví dụ, trong mô hình phát hiện gian lận, Specificity cao tránh được các trường hợp báo động sai (dương giả).

Giải thích: 
- Specificity là tỷ lệ dự đoán đúng các mẫu âm
- Trong trường hợp phát hiện gian lận, các mẫu âm là các giao dịch không gian lận
- Specificity cao có nghĩa là mô hình nhận diện đúng hầu hết các giao dịch không gian lận, tức là giảm thiểu các trường hợp báo động sai (False Positive)

### 4. Giá trị dự đoán dương (Precision)
**Precision** hay còn gọi là **Độ chính xác của các dự đoán dương** là tỷ lệ dự đoán đúng trong số tất cả các mẫu được dự đoán là dương. Precision đặc biệt quan trọng khi chi phí của việc dương giả cao.
$$
\text{Precision} = \frac{TP}{TP + FP}
$$

Ví dụ, trong mô hình phát hiện ung thư, Precision cao đảm bảo rằng những trường hợp bị đánh dấu là dương (bệnh nhân mắc ung thư) có khả năng mắc bệnh thực sự.

Giải thích:
- Precision là tỷ lệ dự đoán đúng trong số tất cả các mẫu được dự đoán là dương
- Trong trường hợp phát hiện ung thư, các mẫu dương là các bệnh nhân được dự đoán mắc ung thư
- Precision cao có nghĩa là hầu hết các bệnh nhân được dự đoán mắc ung thư thực sự mắc bệnh, tức là giảm thiểu các trường hợp dương giả (False Positive)

### 5. F1-Score
**F1 Score** là trung bình điều hòa giữa Precision và Recall. Chỉ số này hữu ích khi cần cân bằng giữa Recall và Precision, đặc biệt trong các bài toán mà một chỉ số cao hơn có thể dẫn đến một chỉ số khác bị giảm.
$$
F1 = \frac{2 \times \text{Precision} \times \text{Recall}}{\text{Precision} + \text{Recall}}
$$

F1 Score giúp đánh giá mô hình với dữ liệu không cân bằng, chẳng hạn như khi số lượng mẫu dương và âm chênh lệch đáng kể.

## Tóm tắt
| Chỉ số       | Công thức                                       | Ý nghĩa |
|--------------|-------------------------------------------------|---------|
| Accuracy     | $$\frac{TP + TN}{TP + TN + FP + FN}$$           | Tỷ lệ dự đoán đúng trên tổng số mẫu |
| Recall       | $$\frac{TP}{TP + FN}$$                          | Tỷ lệ phát hiện đúng các mẫu dương |
| Specificity  | $$\frac{TN}{TN + FP}$$                          | Tỷ lệ phát hiện đúng các mẫu âm |
| Precision    | $$\frac{TP}{TP + FP}$$                          | Tỷ lệ các dự đoán dương chính xác |
| F1-Score     | $$\frac{2 \times \text{Precision} \times \text{Recall}}{\text{Precision} + \text{Recall}}$$ | Cân bằng giữa Precision và Recall |


# Bài tập nhẹ nhàng

### Cho ma trận nhầm lẫn sau: 
$$
\begin{bmatrix}
50 & 10 \\
5 & 30 \\
\end{bmatrix}
$$

1. Định nghĩa ma trận nhầm lẫn
2. Tính toán các chỉ số
3. In kết quả

In [1]:
# Định nghĩa ma trận nhầm lẫn
TN = 50 # thầy Anh bảo code here
FP =  10     # thầy Anh bảo code here   
FN = 5# thầy Anh bảo code here
TP = 30# thầy Anh bảo code here
# Tính toán các chỉ số
accuracy = (TP + TN) / (TP + TN + FP + FN)# thầy Anh bảo code here
recall = TP / (TP + FN)# thầy Anh bảo code here
specificity =TN / (TN + FP)# thầy Anh bảo code here
precision = TP / (TP + FP)# thầy Anh bảo code here
f1 = 2 * (precision * recall) / (precision + recall)# thầy Anh bảo code here
# In kết quả
print(f"Confusion Matrix:\n[[{TN} {FP}]\n [{FN} {TP}]]")# thầy Anh bảo code here
print(f"Accuracy: {accuracy:.2f}")# thầy Anh bảo code here
print(f"Recall: {recall:.2f}")# thầy Anh bảo code here
print(f"Specificity: {specificity:.2f}")# thầy Anh bảo code here
print(f"Precision: {precision:.2f}")# thầy Anh bảo code here
print(f"F1 Score: {f1:.2f}")# thầy Anh bảo code here

Confusion Matrix:
[[50 10]
 [5 30]]
Accuracy: 0.84
Recall: 0.86
Specificity: 0.83
Precision: 0.75
F1 Score: 0.80


In [2]:
# Nhận xét ở đây:
# mô hình này có độ chính xác là 84% 
# Giá trị Recall cho thấy 86% các mẫu thực sự thuộc lớp dương (positive) đã được mô hình dự đoán đúng
# Giá trị Precision cho thấy 75% các mẫu dự đoán là dương (positive) thực sự
#Giá trị Specificity là 83%, nghĩa là mô hình dự đoán đúng 83% các trường hợp thuộc lớp âm (negative)
#giá trị F1 Score là 0.80, là sự kết hợp giữa Precision và Recall. Điều này cho thấy sự cân bằng giữa độ chính xác của mô hình 
# tổng kết mô hình này cho thấy độ chính xác khá tốt và sự cân bằng giữa  Precision và Recall khá ok:)))

## Bài tập nâng cao

### Sủ dụng Markfown để viết ra 4 chỉ số tính độ chính xác, và viết định nghĩa cho các công thức sau:

1. Balanced Accuracy
2. Matthews Correlation Coefficient (MCC)
3. Fowlkes-Mallows Index (FMI)
4. Bias

### Ứng dụng 4 chỉ số này để tính toán cho bài tập nhẹ nhàng ở trên

**Balanced Accuracy** là trung bình recall và specificity dùng để đánh giá hiệu suất phân loại

**Công thức**:
$$
\text{Balanced Accuracy} = \frac{\text{Recall} + \text{Specificity}}{2}
$$
**Matthews Correlation Coefficient (MCC)** là thước đo hiệu suất tổng thể của mô hình phân loại nhị phân. Giá trị của nó dao động từ -1 đến 1
- 1 là dự đoán hoàn toàn tốt
- 0 là dự đoán ngẫu nhiên
- -1 là dự đoán hoàn toàn xấu

**Công thức**:
$$
\text{MCC} = \frac{(TP \times TN) - (FP \times FN)}{\sqrt{(TP + FP)(TP + FN)(TN + FP)(TN + FN)}}
$$
**Fowlkes-Mallows Index (FMI)** đo lường mức độ chặt chẽ . Nó cho thấy sự cân đối giữa Precision và Recall.

**Công thức**:
$$
\text{FMI} = \sqrt{\frac{TP}{TP + FP} \times \frac{TP}{TP + FN}}
$$
**Bias** là tỷ lệ giữa tổng số dự đoán dương tính và tổng số mẫu.

**Công thức**:
$$
\text{Bias} = \frac{TP + FP}{TP + TN + FP + FN}
$$


In [3]:
# thầy Thái Anh bảo codehere
# đầu tiên là import thư viện nè
import math
#giá trị từ bài tập trước
TN = 50 
FP =  10  
FN = 5
TP = 30
#các thông số cần để tính toán
accuracy = (TP + TN) / (TP + TN + FP + FN)
specificity =TN / (TN + FP)
precision = TP / (TP + FP)
#tính toán Balanced Accuracy
Balanced_Accuracy= (recall + specificity) / 2
#tính toán MCC nè thầy
MCC=((TP * TN) - (FP * FN)) / math.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
#tính toán FMI luôn nè
FMI=math.sqrt(precision * recall)
#tính toán bias cuối cùng
Bias=(TP + FP) / (TP + TN + FP + FN)
#in kết quả ra nè thầy uii
print(f"Balanced Accuracy: {Balanced_Accuracy:.2f}")
print(f"Matthews Correlation Coefficient (MCC): {   MCC:.2f}")
print(f"Fowlkes-Mallows Index (FMI): {FMI:.2f}")
print(f"Bias: {Bias:.2f}")              


Balanced Accuracy: 0.85
Matthews Correlation Coefficient (MCC): 0.67
Fowlkes-Mallows Index (FMI): 0.80
Bias: 0.42


In [4]:
#Nhận xét của 
#chì số cân bằng khá tốt nằng ở độ 85% tuy nhiên chỉ số MCC là 67% cũng khá ổn định và 2 chỉ số cuối cùng là 
#FMI có giá trị là 0.80, điều này chỉ ra rằng mô hình có sự cân đối tốt giữa Precision và Recall. 
#Giá trị Bias là 0.42, thể hiện tỷ lệ các dự đoán dương tính trên tổng số mẫu.

## Bài tập vận dụng

In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
# Tạo dữ liệu giả định cho KNN
np.random.seed(42)
data_size = 1000
# Tạo các đặc trưng ngẫu nhiên giữa các lớp
X_class0 = np.random.multivariate_normal([2, 2], [[1.5, 0.75], [0.75, 1.5]], data_size // 2)
X_class1 = np.random.multivariate_normal([4, 4], [[1.5, 0.75], [0.75, 1.5]], data_size // 2)
X = np.vstack((X_class0, X_class1))
y = np.hstack((np.zeros(data_size // 2), np.ones(data_size // 2)))
# Chia dữ liệu thành tập huấn luyện và tập kiểm tra với test = 30 và random = 42
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Hiển thị một vài mẫu dữ liệu
print(pd.DataFrame(X_train[:5], columns=["Feature 1", "Feature 2"]))
print("Nhãn tương ứng:", y_train[:5])

   Feature 1  Feature 2
0   3.069402   5.612889
1  -0.355127  -1.005306
2   1.213291   2.977067
3   1.521887   2.125014
4   3.522842   2.539153
Nhãn tương ứng: [1. 0. 0. 0. 1.]


In [6]:
def euclidean_distance(a, b):
    return np.sum((a - b) ** 2)
def knn_predict(X_train, y_train, X_test, k=5):
    y_pred = []
    for test_point in X_test:
        distances = [euclidean_distance(test_point, x) for x in X_train]
        k_indices = np.argsort(distances)[:k]
        k_nearest_labels = [y_train[i] for i in k_indices]
        most_common = max(set(k_nearest_labels), key=k_nearest_labels.count)
        y_pred.append(most_common)
    return np.array(y_pred)
# Dự đoán trên tập kiểm tra với k = 5
y_pred_knn = knn_predict(X_train, y_train, X_test, k=5)

In [7]:
# Định nghĩa hàm confusion_matrix
def confusion_matrix(y_true, y_pred):
    TP = np.sum((y_true == 1) & (y_pred == 1)) #code here
    TN = np.sum((y_true == 0) & (y_pred == 0))#code here
    FP = np.sum((y_true == 0) & (y_pred == 1))#code here
    FN = np.sum((y_true == 1) & (y_pred == 0)) #code here
    return np.array([[TN, FP], [FN, TP]])#code here

# Hàm tính toán và in các chỉ số
def evaluate_model(y_test, y_pred):
    cm = confusion_matrix(y_test, y_pred)
    TN, FP, FN, TP = cm.ravel()
    accuracy = (TP + TN) / (TP + TN + FP + FN)#code here
    recall = TP / (TP + FN)#code here
    specificity =TN / (TN + FP)#code here
    precision = TP / (TP + FP)#code here
    f1 = 2 * (precision * recall) / (precision + recall) #code here
    print(f"Confusion Matrix:\n{cm}")
    print(f"Accuracy: {accuracy:.2f}")
    print(f"Recall: {recall:.2f}")
    print(f"Specificity: {specificity:.2f}")
    print(f"Precision: {precision:.2f}")
    print(f"F1 Score: {f1:.2f}")
# Đánh giá mô hình KNN
print("KNN Model Evaluation:")
cm= evaluate_model(y_test, y_pred_knn)

KNN Model Evaluation:
Confusion Matrix:
[[116  34]
 [ 16 134]]
Accuracy: 0.83
Recall: 0.89
Specificity: 0.77
Precision: 0.80
F1 Score: 0.84


# Bài tập về nhà

### Tải tập dữ liệu Wine từ sklearn.datasets và chia tập dữ liệu theo tỷ lệ 70:30. Xây dựng mô hình KNN để phân loại dữ liệu. Sử dụng k = 5. Tính toán và in ra độ chính xác, recall, và precision của mô hình
### Xây dựng website để trực quan hóa kết quả và độ chính xác

In [8]:
#Code here
#các hàm cần thiết 
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_wine

In [9]:
#Code here
data = load_wine()
X, y = data.data, data.target

In [10]:
#Code here
# chia dữ liệu kiểm tra 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print(X_train)
print(X_test)

[[1.349e+01 3.590e+00 2.190e+00 ... 8.100e-01 1.820e+00 5.800e+02]
 [1.251e+01 1.730e+00 1.980e+00 ... 1.040e+00 3.570e+00 6.720e+02]
 [1.233e+01 9.900e-01 1.950e+00 ... 1.060e+00 2.310e+00 7.500e+02]
 ...
 [1.438e+01 1.870e+00 2.380e+00 ... 1.200e+00 3.000e+00 1.547e+03]
 [1.269e+01 1.530e+00 2.260e+00 ... 9.600e-01 2.060e+00 4.950e+02]
 [1.234e+01 2.450e+00 2.460e+00 ... 8.000e-01 3.380e+00 4.380e+02]]
[[1.364000e+01 3.100000e+00 2.560000e+00 1.520000e+01 1.160000e+02
  2.700000e+00 3.030000e+00 1.700000e-01 1.660000e+00 5.100000e+00
  9.600000e-01 3.360000e+00 8.450000e+02]
 [1.421000e+01 4.040000e+00 2.440000e+00 1.890000e+01 1.110000e+02
  2.850000e+00 2.650000e+00 3.000000e-01 1.250000e+00 5.240000e+00
  8.700000e-01 3.330000e+00 1.080000e+03]
 [1.293000e+01 2.810000e+00 2.700000e+00 2.100000e+01 9.600000e+01
  1.540000e+00 5.000000e-01 5.300000e-01 7.500000e-01 4.600000e+00
  7.700000e-01 2.310000e+00 6.000000e+02]
 [1.373000e+01 1.500000e+00 2.700000e+00 2.250000e+01 1.010000e+

In [11]:
#Code here
#hàm KNN 
def euclidean_distance(a, b):
    return np.sum((a - b) ** 2)
def knn_predict(X_train, y_train, X_test, k=5):
    y_pred = []
    for test_point in X_test:
        distances = [euclidean_distance(test_point, x) for x in X_train]
        k_indices = np.argsort(distances)[:k]
        k_nearest_labels = [y_train[i] for i in k_indices]
        most_common = max(set(k_nearest_labels), key=k_nearest_labels.count)
        y_pred.append(most_common)
    return np.array(y_pred)
# Dự đoán trên tập kiểm tra với k = 5
y_pred_knn = knn_predict(X_train, y_train, X_test, k=5)

In [12]:
#định nghịa cacu
# Định nghĩa hàm confusion_matrix
def confusion_matrix(y_true, y_pred):
    TP = np.sum((y_true == 1) & (y_pred == 1)) #code here
    TN = np.sum((y_true == 0) & (y_pred == 0))#code here
    FP = np.sum((y_true == 0) & (y_pred == 1))#code here
    FN = np.sum((y_true == 1) & (y_pred == 0)) #code here
    return np.array([[TN, FP], [FN, TP]])#code here

# Hàm tính toán và in các chỉ số
def evaluate_model(y_test, y_pred):
    cm = confusion_matrix(y_test, y_pred)
    TN, FP, FN, TP = cm.ravel()
    accuracy = (TP + TN) / (TP + TN + FP + FN)#code here
    recall = TP / (TP + FN)#code here
    specificity =TN / (TN + FP)#code here
    precision = TP / (TP + FP)#code here
    f1 = 2 * (precision * recall) / (precision + recall) #code here
    print(f"Confusion Matrix:\n{cm}")
    print(f"Accuracy: {accuracy:.2f}")
    print(f"Recall: {recall:.2f}")
    print(f"Specificity: {specificity:.2f}")
    print(f"Precision: {precision:.2f}")
    print(f"F1 Score: {f1:.2f}")
# Đánh giá mô hình KNN
print("KNN Model Evaluation:")
cm= evaluate_model(y_test, y_pred_knn)

KNN Model Evaluation:
Confusion Matrix:
[[17  0]
 [ 1 15]]
Accuracy: 0.97
Recall: 0.94
Specificity: 1.00
Precision: 1.00
F1 Score: 0.97
